import { EcosystemApp } from '@site/src/components/Ecosystem/EcosystemBlocks';

export const EcosystemAppsList: EcosystemApp[] = [
  {
    id: 1,
    name: 'Last One',
    description: 'Last one to bid before timer runs out takes the pot',
    icon: '/assets/ecosystem/last-one-icon.png',
    bgImage: '/assets/ecosystem/last-one-bg.png',
    bgGradientColor: '#E5B92A',
    tags: ['Gaming'],
    href: 'https://www.lastone.fun/',
    titleColor: 'black',
    descriptionColor: 'black',
    tagsColor: 'black',
    appoftheweek: true,
  },
  {
    id: 2,
    name: 'Ballsy',
    description: 'Battle for glory by logging in with your favorite chain',
    icon: '/assets/ecosystem/ballsy-icon.png',
    bgImage: '/assets/ecosystem/ballsy-bg.png',
    bgGradientColor: 'rgba(0, 0, 0, 0.80)',
    tags: ['Gaming'],
    href: 'https://ballsy.push.org/',
    titleColor: 'white',
  },
  {
    id: 3,
    name: 'Hodl.fun',
    description: 'Create & launch ERC-20 tokens',
    icon: '/assets/ecosystem/hodl-fun-icon.png',
    bgImage: '/assets/ecosystem/hodl-fun-bg.png',
    bgGradientColor: 'rgba(0, 0, 0, 0.80)',
    tags: ['DeFi'],
    twitterId: '1989664475784663041',
    href: 'https://www.thehodl.fun/',
    titleColor: 'white',
  },
  {
    id: 4,
    name: 'Bountive',
    description: 'Universal growth engine rewarding quality over clicks',
    icon: '/assets/ecosystem/bountive-icon.png',
    bgImage: '/assets/ecosystem/bountive-bg.png',
    bgGradientColor: '#000000',
    tags: ['Social'],
    twitterId: '1989664498920403443',
    href: 'https://bountive.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 5,
    name: 'APT Casino',
    description: 'Universal, fair, & transparent wager to win',
    icon: '/assets/ecosystem/apt-casino-icon.png',
    bgImage: '/assets/ecosystem/apt-casino-bg.png',
    bgGradientColor: '#5E1140',
    tags: ['Gaming'],
    twitterId: '1989664509439713780',
    href: 'https://apt-casino-push-chain.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 6,
    name: 'Push Ninja',
    description: 'On-chain skill based game',
    icon: '/assets/ecosystem/push-ninja-icon.png',
    bgImage: '/assets/ecosystem/push-ninja-bg.png',
    bgGradientColor: '#591D5C',
    tags: ['Gaming'],
    twitterId: '1989664523339665658',
    href: 'https://push-ninja.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 7,
    name: 'OnchainVampireSurvivors',
    description: 'Universal vampire survivors like game',
    icon: '/assets/ecosystem/onchain-vampires-icon.png',
    bgImage: '/assets/ecosystem/onchain-vampires-bg.png',
    bgGradientColor: '#5D261E',
    tags: ['Gaming'],
    twitterId: '1989664518855954717',
    href: 'https://catkevin.github.io/OnchainVampireSurvivors/',
    titleColor: 'white',
  },
  {
    id: 8,
    name: 'TipUp',
    description: 'Tip on any chain using any wallet',
    icon: '/assets/ecosystem/tip-up-icon.png',
    bgImage: '/assets/ecosystem/tip-up-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: '1989664514686783920',
    href: 'https://tip-up-push.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 9,
    name: 'ChainCircle',
    description: 'Cross chain saving circles',
    icon: '/assets/ecosystem/chaincircle-icon.png',
    bgImage: '/assets/ecosystem/chaincircle-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: '1989664436433637415',
    href: 'https://www.chaincircle.org/',
    titleColor: 'white',
  },
  {
    id: 10,
    name: 'EON: AI Butler',
    description: 'Send, swap, and manage assets across supported networks',
    icon: '/assets/ecosystem/eon-icon.png',
    bgImage: '/assets/ecosystem/eon-bg.png',
    bgGradientColor: '#000000',
    tags: ['NFT'],
    twitterId: '1989664469484728745',
    href: 'https://eon-five.vercel.app',
    titleColor: 'white',
  },
  {
    id: 11,
    name: 'Push Swap',
    description: 'Seamless cross-chain token swaps without bridges',
    icon: '/assets/ecosystem/push-swap-icon.png',
    bgImage: '/assets/ecosystem/push-swap-bg.png',
    bgGradientColor: '#DD60C4',
    tags: ['DeFi'],
    twitterId: '1989664440468590639',
    href: 'https://push-swap-sepia.vercel.app/',
    titleColor: 'black',
    descriptionColor: 'black',
    tagsColor: 'black',
  },
  {
    id: 12,
    name: 'Star Run',
    description: 'A decentralized, player-owned economy',
    icon: '/assets/ecosystem/star-run-icon.png',
    bgImage: '/assets/ecosystem/star-run-bg.png',
    bgGradientColor: '#000000',
    tags: ['Gaming'],
    twitterId: '1989664445501751672',
    href: 'https://starrun.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 13,
    name: 'Forge Realm',
    description:
      'Mix and match base characters and traits from multiple creators',
    icon: '/assets/ecosystem/forge-realm-icon.png',
    bgImage: '/assets/ecosystem/forge-realm-bg.png',
    bgGradientColor: '#000000',
    tags: ['NFT'],
    twitterId: '1989664480616464799',
    href: 'https://forge-realm.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 14,
    name: 'Push Name Service',
    description: 'Get your own .push domain',
    icon: '/assets/ecosystem/push-name-service-icon.png',
    bgImage: '/assets/ecosystem/push-name-service-bg.png',
    bgGradientColor: '#000000',
    tags: ['Infra'],
    twitterId: '1989664485427351900',
    href: 'https://push-name-service.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 15,
    name: 'Push Campus',
    description: 'Reach students on Ethereum, Solana, Base, and 15+ chains',
    icon: '/assets/ecosystem/push-campus-icon.png',
    bgImage: '/assets/ecosystem/push-campus-bg.png',
    bgGradientColor: '#000000',
    tags: ['Social'],
    twitterId: '1989664494503743894',
    href: 'https://push-campus.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 16,
    name: 'PNS',
    description: 'Your Identity Across Every Chain',
    icon: '/assets/ecosystem/pns-icon.png',
    bgImage: '/assets/ecosystem/pns-bg.png',
    bgGradientColor: '#4A1756',
    tags: ['Infra'],
    twitterId: '1989664489902575819',
    href: 'https://universal-name-service.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 17,
    name: 'Athera',
    description: 'Automated crypto inheritance',
    icon: '/assets/ecosystem/athera-icon.png',
    bgImage: '/assets/ecosystem/athera-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: '1989664503341129977',
    href: 'https://atherra.vercel.app/',
    titleColor: 'white',
  },
  {
    id: 18,
    name: 'Degen Chess',
    description: 'Play chess, wager, universal',
    icon: '/assets/ecosystem/degen-chess-icon.png',
    bgImage: '/assets/ecosystem/degen-chess-bg.png',
    bgGradientColor: 'rgba(148, 163, 184, 0.25)',
    tags: ['Gaming'],
    href: 'https://degenchess.example.com/',
    titleColor: 'white',
    comingsoon: true,
  },
  {
    id: 19,
    name: 'Hang4.fun',
    description: 'Coming Soon',
    icon: '/assets/ecosystem/hangfun-icon.png',
    bgImage: '/assets/ecosystem/hangfun-bg.png',
    bgGradientColor: 'rgba(148, 163, 184, 0.25)',
    tags: ['TBA'],
    href: 'https://hang4.fun/',
    titleColor: 'white',
    comingsoon: true,
  },
];
